nasa/harmony-py

examples/basic.ipynb, examples/helper.py, examples/job_results.ipynb, harmony/auth.py, harmony/config.py, harmony/harmony.py, tests/test_auth.py, tests/test_client.py
WIP
This PR is for initial review on the approach taken for blocking and non-blocking job methods. Due to limitations with `requests-futures` I continue to use futures for eventual results but rolled in a different file downloading setup. The initial design tried to hide any use of futures from the end user but it ended up being bad, I think, because it removed the ability for the user to cancel downloads early. The current design is blocking on a per download basis but continues to download all other files in parallel up to the thread pool worker size. That means someone may work with / process a file while the others are streaming to disk. Other features present.
Please see examples/job_results.ipynb
=> HARMONY-710: Job results and file downloading

examples/s3_access.ipynb, harmony/harmony.py, requirements/examples.txt
This was a very small card to retrieve a cloud access token. NOTE: no additional unit tests included; I'd be happy to contribute one or more as part of 715.
The review notebook is in examples/s3_access.ipynb
=> HARMONY-712: Added the ability to retrieve a cloud access token for S3 URI's

examples/job_stac.ipynb, harmony/harmony.py, requirements/examples.txt, tests/test_client.py
HARMONY-711: Added arbitrary URL retrieval from Client to support pystac
common usage.
HARMONY-711: Added example STAC notebook job_stac.ipynb.
HARMONY-711: examples.txt requirements file now uses pystac.
This card was just a small effort to retrieve the STAC URL and make it possible to feed STAC data into something like pystac.
The review notebook is in examples/job_stac.ipynb
=> HARMONY-711: Added job STAC URL retrieval in harmony.py.

setup.py
To test:
```
make build
tar -ztf dist/harmony-py-*
```
Verify that the output includes harmony/* and not tests/*
In a clean Python environment, you can 
`pip install dist/harmony-py-*` and/or `pip install -e .` in the harmony-py dir, go to another dir (e.g. /tmp) run `python` and `from harmony import Client` and verify no exception is thrown
=> HARMONY-787: Fix pip package installation

docs/user/notebook.html, harmony/harmony.py, tests/test_client.py
To fix, run the notebook `examples/s3_access.ipynb` and observe that it produces s3 links rather than the https links being produced on the main branch.
=> HARMONY-845: Fix link_type=LinkType.S3 not returning s3:// links

examples/basic.ipynb, examples/intro_tutorial.ipynb, examples/job_results.ipynb, examples/job_stac.ipynb, examples/job_status.ipynb, examples/s3_access.ipynb, examples/shapefile_subset.ipynb, examples/tutorial.ipynb
To test, start a clean kernel with only Jupyter installed and verify the notebooks work.
Note there is one issue that's external to us: intake-stac depends on sat-stac, which depends on a version of dateutils that conflicts with the version Jupyter Lab itself needs.  There's a PR out to sat-stac to fix it, which I pinged @matthewhanson about https://github.com/sat-utils/sat-stac/pull/69 so I'm treating it as external
=> HARMONY-905: Update all notebooks to install their own dependencies

.gitignore, harmony/harmony.py, requirements/core.txt, tests/test_client.py
In some situations, I'd like to be able to see the request that is going to be submitted to Harmony before actually submitting it (in Jupyter notebooks for example).
Thought the easiest way to do that would be to curlify the request since the request can also include POST data content.
=> Add request as curl function

examples/basic.ipynb, examples/tutorial.ipynb, harmony/harmony.py, tests/test_client.py
~Will run `make docs` once I confirm that these changes are ok. Was a little difficult to find a logical place in the user-facing documentation to describe concatenate. Considered adding a new notebook example but I'm guessing someone else will likely do that during demos.~ (resolved)
I can test via a live example once the concatenation service is in available.
=> HARMONY-994: Allow use of concatenate param

harmony/harmony.py, tests/test_request.py
This PR makes a minor change to the bounding box validation within `harmony-py` to ensure that if a user specifies northern and southern extents that are equal, that request is considered valid. This allows a user to specify a single point or horizontal line for subsetting via a bounding box. Harmony itself already supports this behaviour, for example:
```
https://harmony.uat.earthdata.nasa.gov/C1225808238-GES_DISC/ogc-api-coverages/1.0.0/collections/%2FGrid%2FprecipitationCal/coverage/rangeset?forceAsync=true&granuleId=G1240992035-GES_DISC&subset=lat(20%3A20)&subset=lon(160%3A160)
```
This has become recently notable because GES-DISC are hoping to support single-point spatial subsetting via HOSS in production (see [GDDS-166](https://bugs.earthdata.nasa.gov/browse/GDDS-166)).
=> GDDS-166 - Allow bounding box southern and northern extents to be equal.

harmony/harmony.py, tests/test_client.py
Just a little quality of life update.
Added local datetime representation to status output to make it easier to read the times when viewed in a Jupyter notebook. Also updated tests to load examples from directory relative to the test_client.py file instead of relative to the current working directory where tests are being run.
Example of what the output of `status` returns after this change:
```
{
'created_at': datetime.datetime(2021, 2, 19, 18, 47, 31, 291000, tzinfo=tzutc()),
'created_at_local': '2021-02-19T10:47:31-08:00',
'message': 'The job is being processed',
'num_input_granules': 32,
'progress': 0,
'request': 'https://harmony.earthdata.nasa.gov/{collection_id}/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?forceAsync=True&subset=lat(52%3A77)&subset=lon(-165%3A-140)&subse …
```
=> Add human readable dates to status output

harmony/harmony.py, tests/test_client.py, tests/test_request.py
HARMONY-1134
This PR adds the `skip_preview` parameter to `Request`. For now it defaults to `True`, because the library does not yet support pause/resume, so we don't want large jobs to be paused with no way to resume them. I have not modified any of
the notebooks yet for the same reason.
In the `job_status` notebook change the request to 
```
harmony_client = Client(env=Environment.UAT)  # assumes .netrc usage
skip_preview=False
)
```
then execute the first four cells - the status returned should show the job is previewing (or paused if you are slow).
=> HARMONY-1134: Added `skip_preview` flag to `Request`

examples/job_pause_resume.ipynb, harmony/harmony.py, tests/test_client.py, tests/test_request.py
HARMONY-1135
Adds pause/resume to harmony-py and switches the `skip-preview` flag from defaulting to sending `skipPreview=true` to not setting the flag at all (preview will happen by default).
Run `make examples` and then step through the `job_pause_resume.ipynb` notebook.
=> Harmony 1135 harmony-py pause resume

.gitignore, harmony/__init__.py, harmony/harmony.py, tests/test_client.py, tests/test_request.py
HARMONY-1124
Add support for setting dimension subsetting parameters.
Figure out how to test a Jupyter notebook with the code for this branch loaded 😱 .
Open the intro_tutorial notebook and modify the request that it sends with:
```
collection=Collection(id='C1222931739-GHRC_CLOUD'),
variables=['atmosphere_cloud_liquid_water_content'],
format='application/netcdf',
max_results=1,
dimensions=[Dimension(name='foo', min=15.1, max=30),
Dimension(name='bar', min=-120, max=120),
Dimension(name='baz', min=-120),
Dimension(name='bear'),
Dimension(name='apple', max=5.5),
Dimension('arg'),
Dimension('lev', 10.0, 20.0)]
)
```
Note you'll also have to modify the harmony imports to include Dimension:
```
from harmony import BBox, Client, Collection, Request, Dimension
```
Uncomment …
=> HARMONY-1124: Add support for setting dimension subsetting parameters

harmony/harmony.py, tests/test_client.py
HARMONY-1125
Users may specify a dimension range with a minimum or maximum value that is 0. Prior to this change, when the request URL was constructed, there was a check for whether the minimum and maximum were falsy. If so, the value was assumed to mean `'*'`. However, 0 will also evaluate to `False`, meaning `Dimension('dim', 0, 10)` creates a subset parameter of `subset=dim(*:10)`, instead of `subset=dim(0:10)`. This PR addresses this edge-case.
With the updated version of `harmony-py` create a request such as:
```python
from harmony import Client, Collection, Dimension, Environment, Request
harmony_client = Client(env=Environment.UAT)
hoss_named_dims_request = Request(collection=Collection(id='C1238392622-EEDTEST'),
granule_id='G1245840464-EEDTEST', …
```
=> HARMONY-1125 - Allow dimensions to specify dim.min=0 or dim.max=0.

.github/workflows/publish-release.yml, .github/workflows/tests.yml, harmony/harmony.py, requirements/dev.txt, tests/test_client.py
HARMONY-784
harmony-py will now raise the error message contained in the harmony response body when possible.
The ticket specified that we should not use `response.raise_for_status()` when possible so I basically modified all the places that `response.raise_for_status()` was currently being used _and_ where we may receive a Harmony response, and replaced it with the new error helper function that attempts to pull out the harmony error message.
I also modified some github action versions to get rid of deprecation warnings. I will take a look at the other python repos to see if they need to be updated as well.
You may also be wondering why I had to write `if hasattr(response_json, 'get'):`. During testing I discovered that `response.json()` might return a string.
Set up a virtual …
=> Harmony 784 - harmony-py should raise the error message contained in the harmony response body when possible

harmony/harmony.py, tests/test_client.py, tests/test_request.py
HARMONY-1215
This adds the new destination URL parameter to the harmony-py client. I want to hold off on merging this until Harmony fully supports this parameter.
Make a harmony-py request using the new parameter and check to make sure that destination URL was included in the request URL.
=> HARMONY-1215: Add destination url

harmony/harmony.py, tests/test_client.py
HARMONY-1376
This modifies the status method to check for a data expiration field rather than assuming that it exists. There are some cases, like when destination_url is passed where the expiration field will not be returned from harmony and thus cannot be returned to users of harmony-py.
After activating your virtual environment, `pip install -e .` to get this branch version of harmony-py in your virtual environment.
Run through notebooks/examples/basic.ipynb. Modify the request to pass in a destination_url. E.g.:
```
destination_url='s3://my-bucket'
)
```
The request should succeed if your bucket has the proper settings, and the notebook cell that calls the job …
=> HARMONY-1376: Don't expect data expiration for every job status

examples/intro_tutorial.ipynb, examples/s3_access.ipynb, examples/tutorial.ipynb, harmony/harmony.py, requirements/examples.txt, tests/test_client.py
HARMONY-1355
Adds the new UMM grid name parameter.
After activating your virtual environment, `pip install -e .` to get this branch version of harmony-py in your virtual environment.
Run through notebooks/examples/basic.ipynb. Modify the request to pass in a grid name. E.g.:
```
grid='LambertDurbin'
)
```
Inspect the request URL after submitting the job: https://harmony.uat.earthdata.nasa.gov/workflow-ui -- you should see `&grid=`.
Add an invalid grid name if you want to see an error.
=> HARMONY-1355: Add UMM grid name parameter

README.md, examples/intro_tutorial.ipynb, harmony/auth.py, harmony/harmony.py
HARMONY-720
As a user, I want to authenticate to Harmony using the Python library with long-lived Earthdata Login tokens
export EDL_TOKEN=<your_EDL_token>
Run `make examples` in harmony-py to start the notebooks
verify `examples/intro_tutorial.ipynb` notebook works.
=> HARMONY-720: Added EDL token support in harmony-py.

harmony/harmony.py
DAS-1606
This is a quick fix for gzipped files being downloaded with the incorrect extension.
slack discussion thread
https://nsidc.slack.com/archives/CLC2SR1S6/p1685051702665579
Pull this branch and install the library into a isolated python environment.
start a repl and run these commands:
``` python
from harmony import Environment, Client
harmony_client = Client(env=Environment.SIT)
theurl = 'https://harmony.sit.earthdata.nasa.gov/service-results/harmony-sit-staging/public/e8ae74fc-55f4-48c4-a94f-b9d0afe6cf9d/1513588/ASTGTMV003_N00E022_dem.jpg.aux.xml'
future = harmony_client.download(theurl, directory='.', overwrite=True)
print(future.result())
```
Ensure the downloaded file is in fact xml by opening it or running this command:
```sh
file ./ASTGTMV003_N00E022_dem.jpg.aux.xml
```
The …
=> Limit accepted encodings in _download_file

harmony/harmony.py, tests/test_client.py
HARMONY-848
This pull request adds logic that throws an exception if a user attempts to download zarr file(s).
- check out this branch
- download harmony-py in your virtual env `pip install -e path/to/local/harmony-py`
- make a harmony-py request and try download and download all (both should raise a zarr exception message):
```
from harmony import BBox, Client, Collection, Request, Environment
harmony_client = Client(auth=(username.value, password.value), env=Environment.UAT)
format='application/x-zarr',
max_results=1,
)
job1_id = harmony_client.submit(request)
[f.result() for f in harmony_client.download_all(job1_id)] …
```
=> Harmony 848 - Zarr output + download_all clarification

harmony/harmony.py, tests/test_client.py
HARMONY-1568
Adds the extend param for passing a list of dimensions in the request.
After activating your virtual environment, pip install -e . to get this branch version of harmony-py in your virtual environment.
Run through notebooks/examples/basic.ipynb. Modify the request to pass in `extend`. E.g.:
extend=['lat', 'lon']
)
Inspect the request URL after submitting the job: https://harmony.uat.earthdata.nasa.gov/workflow-ui -- you should see `&extend=...`.
=> HARMONY-1568: Add extend param

examples/intro_tutorial.ipynb
HARMONY-1611
Fixed intro_tutorial.ipynb to render in github.
https://github.com/nasa/harmony-py/blob/harmony-1611/examples/intro_tutorial.ipynb now renders correctly.
=> HARMONY-1611: Fixed intro_tutorial.ipynb to render in github.

.github/workflows/tests.yml, README.md, examples/basic.ipynb, examples/job_stac.ipynb, harmony/harmony.py, requirements/core.txt, requirements/dev.txt, requirements/docs.txt, requirements/examples.txt
N/A
I was in the Snyk UI and spotted `harmony-py` has a critical vulnerability in `requirements/example.txt`. This PR addresses the vulnerability by updating the dependencies for the notebooks in the `examples` directory. I also bumped the requirements in `requirements/docs.txt`, as there was a medium severity vulnerability there (`tornado` via `nbconvert`).
I checked things still worked by running the notebooks in the `examples` directory. Most ran, but there were a couple of exceptions:
* `job_stac.ipynb` couldn't find `pystac.STAC_IO`, so I changed that to `pystac.stac_io`, which seemed to work.
* The `helper.show_results` in `basics.ipynb` failed for a bunch of requests that were getting NetCDF-4 files out of HGA. I fixed this by forcing all the requests to give GeoTIFF outputs.
* …
=> Update Snyk vulnerabilities in documentation

harmony/harmony.py, tests/test_client.py
HARMONY-1721
harmony-py was using a GET for all calls to harmony, but this was causing 413 issues when trying to use a long list of granuleIds because of URL length limits. This PR switches to use a POST with multipart/form-data (we were already doing this when a shapefile was included in the request).
Run `make test` and verify all tests pass.
Run the first request in the `examples/tutorial.ipynb` notebook. Note that there's a bug in harmony parsing width and height which will be addressed as a separate ticket. So you'll need to comment those out so the cell looks like this:
```
temporal={
'start': dt.datetime(2010, 1, 1),
'stop': dt.datetime(2020, 12, 30)
}, …
```
=> HARMONY-1721: Switch from using GET to a POST in all OGC coverages calls to harmony

examples/tutorial.ipynb, harmony/harmony.py, tests/test_client.py
HARMONY-1752
Adds a new method to the `Client` class, `request_as_url` that returns a URL string that can be pasted into a browser.
Run the tutorial.ipynb notebook. The ninth code cell will output a URL string. Paste this into a browser and verify that it runs a Harmony job.
=> Harmony 1752

.github/workflows/publish-release.yml, harmony/__init__.py
HARMONY-1756
Changes GitHub publish action to use trusted publisher token instead of password stored in GitHub secret.
1. Click on the 'Releases' link in the main page of this GitHub repo
2. Click on 'Draft release' button.
3. Create a dummy tag
4. Choose this branch instead of 'main'
5. Fill in title and description with whatever
6. Choose "pre-production release" checkbox
7. Click on 'Publish release'
8. Check to the 'Actions' tab on the page and make sure the publish action succeeds
9. Go to pypi.org and search for harmony-service-lib
10. Check on the releases and verify that your release is there
11. Delete your test release
=> Harmony 1756 - Use trusted publisher to publish to PyPi

.gitignore, harmony/harmony.py, tests/test_client.py
HARMONY-1762
Change to pass the variables in the query parameters using `parameter_vars` so that we can support requests with 4000+ variables.
I tested with the intro_tutorial notebook and modifying the request to use a bounding box instead of a shapefile (the request_as_url and request_as_curl methods do not work with a shapefile).
Add a couple print statements to the notebooks to see what the URL looks like:
print(harmony_client.request_as_url(request))
print(harmony_client.request_as_curl(request))
Make sure you see it uses `parameter_vars` and the variable is included in the query parameters.
Also test removing the variables altogether and make sure it passes `variable=all`.
It would be good to test with a large number of variables as well if someone has a good request for that.
=> HARMONY-1762: Switch to passing variables in the query parameters

requirements/docs.txt
HARMONY-1793
This fixes the warning message in readthedocs for shapely module.
The warning message about `No module named 'shapely'` in readthedocs build is gone.
=> HARMONY-1793: Fixed warning message in readthedocs for shapely module.

.github/workflows/publish-release.yml, .github/workflows/tests.yml, README.md, setup.py
HARMONY-1838
1. Clarifies supported python versions (to address https://github.com/nasa/harmony-py/issues/78)
2. Updates some deprecated GitHub actions. 
3. Modifies the "Tests" GitHub workflow so that detailed HTML code coverage reports are only uploaded to GitHub on pull request open or synchronize events. (For every commit, the tests will still run and the code coverage summary will still be printed to the GitHub actions web UI). If developers want the full HTML coverage report outside of pull requests, it can be generated locally, on demand via `make test`.
run `make ci`
=> Harmony 1838 - Clarify supported python versions

examples/tutorial.ipynb, harmony/harmony.py
HARMONY-1859
Add WKT POINT support in harmony-py.
make examples
Then run tutorial notebook, modify the spatial parameter for the last test to use POINT or MULTIPOINT, e.g. 
`spatial=WKT('POINT(-40 10)'),`
or 
`spatial=WKT('MULTIPOINT((-77 38.9),(-40 10))'),`
Verify the harmony-py request is submitted as EDR position request in harmony and runs successfully.
=> HARMONY-1859: Add WKT POINT support in harmony-py.

.github/workflows/tests.yml, README.md, pyproject.toml
HARMONY-1646
Drop support for end of life Python 3.8. Add tests for Python 3.12 and 3.13.
Set up environments for 3.9, 3.10, 3.11, 3.12, and 3.13
Verify installation and tests work in each env.
1. make install
2. make lint
3. make docs
4. make test
5. make examples
Test out the intro notebook to make sure things work as expected except for the known issue with STAC items not loading due to performance problems.
=> HARMONY-1646: Update supported Python versions to 3.9 through 3.13.

harmony/harmony.py, tests/test_client.py
HARMONY-1929
Since opendap can have potentially very long data download URLs we need to ensure that we convert the query string to POST body parameters in those cases and submit a POST request.
**_NOTE:_** I did see OPeNDAP timing out for very long URLs.
The snyk check is failing due to an internal snyk error.
This is how I tested:
1. With a local harmony instance running, submit a request.
2. Once it finishes, change one of the job link data URLs in the job links table to:
https://opendap.uat.earthdata.nasa.gov/collections/C1261703111-EEDTEST/granules/SC:ATL03.006:264549068.dap.nc4?dap4.ce=/ds_surf_type[0:1:4]
3. Copy the job ID for this job as you will use it to make a download request with harmony-py.
4. Create a virtual environment with this version of harmony-py installed (`pip …
=> Harmony 1929 - Ensure OPeNDAP downloads use POST

harmony/harmony.py, tests/test_client.py
HARMONY-1929
A follow up/revision to https://github.com/nasa/harmony-py/pull/97 (removes colons from downloaded file name).
`make test`
or for an end-to-end test see https://github.com/nasa/harmony-py/pull/97
=> Harmony 1929-2: Remove colon from downloaded file name

examples/basic.ipynb, examples/intro_tutorial.ipynb, harmony/harmony.py, tests/test_client.py
HARMONY-1936
This PR adds a default label of 'harmony-py' to jobs created with this library. It can be disabled by setting the environment variable `EXCLUDE_DEFAULT_LABEL` to "true".
1. Run the example/basic.ipynb notebook.
2. Verify that the created job has a 'harmony-py' label
3. set the `EXCLUDE_DEFAULT_LABEL` env var to "true"
4. Run the example notebook again.
5. Verify that the created job has no label.
=> Harmony 1936: Add default job label to harmony-py jobs

harmony/harmony.py, pyproject.toml, tests/test_client.py
HARMONY-1993
Allows users to set custom labels on harmony requests.
Note that I also upgraded some libraries to eliminate several warnings.
Bring up one of the notebooks like `tutorial.ipynb`. Modify a request to set labels by adding `labels=['foo', 'bar']` to the request constructor. Verify that the harmony request that gets created includes the labels 'foo', 'bar', and 'harmony-py'.
Repeat the test after setting the environment variable `EXCLUDE_DEFAULT_LABEL=true`. Verify that the labels 'foo' and 'bar' are included in the request, but not 'harmony-py'.
Verify that submitting a request without any labels field also works.
=> HARMONY-1993: Allow users to set custom labels for harmony requests.

docs/api.rst, examples/intro_tutorial.ipynb, examples/job_label.ipynb, harmony/__init__.py, harmony/harmony.py, tests/test_client.py, tests/test_request.py
HARMONY-1906
Add JobsRequest to get a list of jobs with page and limit.
Run `examples/job_label.ipynb` for jobs examples.
=> HARMONY-1906: As a user, I want to see a list of my jobs using harmony-py.

.github/workflows/tests.yml
HARMONY-2011
This PR addresses the pending deprecation of the ubuntu-20.04 runner image for GitHub workflows. For more information, see:
https://github.com/actions/runner-images/issues/11101
N/A - mainly we need to see that the test workflow runs without any weirdness.
* ~~Documentation updated (if needed)~~
=> HARMONY-2011 - Update tests.yml workflow to use ubuntu-latest runner.

harmony/client.py
HARMONY-1997
Updated harmony-py to report error when there is no files to download for failed or warning requests during `client.download_all` invocation.
Since we have to use customized (fake) service image to get requests into warning state, it doesn't make sense to add a notebook to demonstrate this behavior. Also the current failed request notebook is returning success probably due to recent configuration changes which we will have to fix as a separate issue (HARMONY-2034).
Here is a notebook snippet to test the error reporting for warning request. I will restore the faked service-example image in UAT once this PR is merged.  
```
import helper
helper.install_project_and_dependencies('..', libs=['examples'])
import json
import sys
import datetime as dt
from harmony import BBox, …
```
=> HARMONY-1997: As a harmony-py user I would like to see a warning message when a job results in no data.

harmony/client.py, harmony/request.py, tests/test_request.py
HARMONY-2035
This PR is the harmony-py part to support client requesting pixel subsetting. There is a corresponding harmony PR that should be used to test the harmony-py change.
It adds a new `pixel_subset` parameter in  harmony-py request to support pixel subsetting.
The `pixel_subset` parameter can be unset, `True` or `False` in a harmony-py request. Feel free to experiment with different values in the following tests.
Use the following block to test OGC Rangeset requests:
```
import helper
helper.install_project_and_dependencies('..', libs=['examples'])
import json
import sys
import datetime as dt
from harmony import BBox, Client, Collection, Request, Environment
harmony_client = Client(env=Environment.LOCAL)
collection = Collection(id='C1233800302-EEDTEST') …
```
=> HARMONY-2035: As a harmony-py user, I want to request pixel subsetting.

examples/job_pause_resume.ipynb, examples/job_status.ipynb, harmony/client.py, tests/test_client.py
HARMONY-2026
Add support in harmony-py to cancel a job.
Add cancel job example in Jupyter notebook.
Fix broken job preview example in Jupyter notebook.
run `job_pause_resume.ipynb` notebook
=> HARMONY-2026: As a client, I want to cancel a job using harmony-py.

.github/CODEOWNERS
HARMONY-2077
Add CODEOWNERS file to make github auto-add reviewers to PRs
None
=> HARMONY-2077: Add CODEOWNERS file to make github auto-add reviewers to PRs

harmony/request.py, tests/test_request.py
HARMONY-2166
Added the 'average' parameter, which is used by the Cloud Giovanni averaging service, to request.py. I wasn't sure if this needed an update to unit tests or not. The 'average' parameter is not validated because it will expand beyond the current two options. I checked your request.py tests and I don't see a test for 'variable', which is similarly not validated in the request.py module, so I decided that meant you didn't need a test. Please let me know if this is incorrect.
I wasn't sure how to handle documentation since this service isn't in production yet.
The averaging service is only in UAT at this time, so you'll need to make the request against that baseline.
```
from harmony import Dimension, Client, Collection, Request, Environment
import datetime as dt
import os …
```
=> HARMONY-2166: Added average parameter to request.py
