- .github/workflows/python-package.yml
- tests/test_placeholder.py
Add a GitHub Actions workflow definition to run linting and unit tests.
> Harmony 716

- .github/workflows/python-package.yml
- README.md
> Kevin test

- .gitignore
- examples/basic.ipynb
- examples/helper.py
- examples/job_status.ipynb
- harmony/config.py
- harmony/harmony.py
- requirements/core.txt
- tests/test_client.py
- tests/test_config.py
Added status() method to Client, submit() now returns job_id, and various other changes.
> Harmony 709: receive status messages from Harmony after submitting data requests

- README.md
- examples/basic.ipynb
- harmony/harmony.py
- tests/test_client.py
Changes that were in HARMONY-754 but got lost due to the way I merged and rebased. Added some README format fixes.
> Harmony 754 new

- harmony/harmony.py
- tests/test_client.py
To test, go to https://harmony.earthdata.nasa.gov/jobs and choose a job in the "failed" state.  If you don't have one, try switching to UAT and updating the code below accordingly.
Run the following (assumes prod and correct .netrc setup):
```python
from harmony import Client
job_id = 'YOUR_FAILED_JOB_ID_HERE'
harmony_client = Client()
data = harmony_client.result_json(job_id)
print(data)
harmony_client.wait_for_processing(job_id, show_progress=True)
```
> HARMONY-785, HARMONY-786: Improve error handling for failed jobs

- harmony/harmony.py
- tests/test_client.py
This PR:
1. adds user-agent headers when a request is submitted via Client
2. adds tests to make sure the user-agent headers are being added with the expected format.
> Harmony 801

- .github/release-drafter.yml
- .github/workflows/draft-release.yml
- .github/workflows/publish-release.yml
Copies the equivalent code from harmony-service-lib-py
> HARMONY-833: Actions for drafting and publishing releases

- .github/workflows/publish-release.yml
- harmony/__init__.py
Released using this branch to PyPI to verify it working
https://pypi.org/project/harmony-py/
> HARMONY-845: Fix PyPI publication action

- harmony/harmony.py
- tests/test_client.py
To test:
1. Verify that notebooks still work (basic.ipynb is the most comprehensive)
2. Edit the return value of _status_url so it has a tiny page size.  So, append `&limit=2` to the string on line 339 of harmony/harmony.py
3. Restart any notebook kernels and rerun the notebooks
> HARMONY-796: Add support for paging result links

- examples/intro_tutorial.ipynb
- examples/shapefile_subset.ipynb
Fix a few small issues and replace a collection that seems to no longer be accessible.
> Harmony 928

- examples/job_pause_resume.ipynb
- harmony/harmony.py
HARMONY-1135
This PR just cleans up some things related to the notebook for pause/resume
* run `make examples`
* open and step through the `pause and resume' notebook
> HARMONY-1135: Clean up notebook and warnings for paused state

- README.md
HARMONY-1313
Just a small documentation update since we started leveraging GitHub releases and actions.
> HARMONY-1313: Update Building and Releasing documentation

- .readthedocs.yml
- README.md
- docs/conf.py
- docs/index.rst
- requirements/dev.txt
- requirements/docs.txt
HARMONY-866
Fixed harmony-py API docs generation
run `make docs` and verify the docs are available at `file:///<your root directory>/harmony-py/docs/_build/html/index.html`
> HARMONY-866 Fixed docs generation.

- docs/api.rst
HARMONY-720
Updated readthedocs documentation for creating harmony-py client with EDL token.
> HARMONY-720: Updated API doc for creating harmony-py client with EDL token.

- .readthedocs.yml
- harmony/harmony.py
HARMONY-720
One more update to the API doc for using EDL token to create Harmony client.
> HARMONY-720: One more update to the API doc.

- examples/job_status.ipynb
- harmony/harmony.py
- tests/test_request.py
HARMONY-1270
Added ignore_errors to harmony-py.
run `make examples` to start examples notebooks, then run `job_status` notebook and verify the notebook adequately demonstrated `ignore_errors` use case in harmony-py.
> HARMONY-1270: Added ignore_errors to harmony-py.

- examples/tutorial.ipynb
- harmony/harmony.py
- requirements/dev.txt
HARMONY-1414
Added support to harmony requests that completes successfully without creating a job.
Run last demo of tutorial notebook and verify the result returned from harmony client submission call is the download links in the harmony request response.
> HARMONY-1414: Added support to harmony requests that completes successfully without creating a job.

- MANIFEST.in
N/A
The `harmony-py` source distribution is currently broken because the requirement files are loaded in `setup.py`:
https://github.com/nasa/harmony-py/blob/main/setup.py#L17-L23
but are not included in the source distribution [distributed on PyPI](https://pypi.org/project/harmony-py/#files).
For the [conda-forge recipe](https://github.com/conda-forge/staged-recipes/pull/25149), which is built from the source distribution, this required me to add a patch to the `setup.py` (patch file generated from  #76). 
This PR [grafts](https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#) the `requirements` directory into the source distribution.
To reproduce:
```shell
$ git clone https://github.com/nasa/harmony-py.git && cd harmony-py
$ python -m pip install --upgrade setuptools
$ …
```
> Include requirements files in source distribution

- README.md
- examples/basic.ipynb
- examples/collection_capabilities.ipynb
- examples/intro_tutorial.ipynb
- examples/job_pause_resume.ipynb
- examples/job_results.ipynb
- examples/job_results_iterator.ipynb
- examples/job_stac.ipynb
- examples/job_status.ipynb
- examples/tutorial.ipynb
- harmony/__init__.py
- harmony/harmony.py
- requirements/core.txt
- tests/test_request.py
HARMONY-1745
As a HarmonyPy user, I want to be able to access the Harmony OGC EDR API so that I can make WKT requests
Run harmony locally under branch harmony-1770 which has the EDR WKT support.
Change `examples/tutorial.ipynb` notebook to point to LOCAL environment and verify the WKT example at the end of the notebook runs successfully and a POST request to local EDR area endpoint with the intended WKT spatial parameter is submitted to Harmony and the request completes successfully.
> HARMONY-1745: As a HarmonyPy user, I want to be able to access the Harmony OGC EDR API so that I can make WKT requests

- requirements/dev.txt
HARMONY-1793
Fixed Snyk test failure
All github actions should run successfully including snyk ones.
> HARMONY-1793: Fixed Snyk test failure

- docs/api.rst
- examples/labels.ipynb
- harmony/__init__.py
- harmony/harmony.py
- tests/test_client.py
- tests/test_request.py
HARMONY-1898
As harmony-py user, I want to be able add one or more labels to one or more of my jobs
Run labels notebook and verify adding labels to jobs work as expected. 
Verify readthedocs documentation is ok.
> HARMONY-1898: As harmony-py user, I want to be able add one or more labels to one or more of my jobs

- docs/api.rst
- examples/job_label.ipynb
- harmony/__init__.py
- harmony/client.py
- harmony/request.py
- tests/test_client.py
- tests/test_request.py
HARMONY-1899
Add delete labels capability in harmony-py via the DeleteLabelsRequest.
Update readthedocs API for DeleteLabelsRequest.
Run examples/job_label.ipynb for removing labels from jobs example.
> HARMONY-1899: As a harmony-py user, I want to be able to remove one or more labels from one or more of my jobs.

- .gitignore
- examples/job_status.ipynb
HARMONY-2034
Update ignore_errors example in Jupyter notebook.
Run examples/job_status.ipynb notebook.
> HARMONY-2034: Update ignore_errors example in Jupyter notebook.
